# Generated by Django 3.1.2 on 2021-10-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Sport'), (2, 'Cars'), (3, 'Clothing'), (4, 'Homelike'), (5, 'Electronic'), (6, 'Games'), (7, 'Miscellaneous')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
