# Generated by Django 3.1.2 on 2021-10-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211006_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cat', models.IntegerField(choices=[(1, 'Sport'), (2, 'Cars'), (3, 'Clothing'), (4, 'Homelike'), (5, 'Electronic'), (6, 'Games'), (7, 'Miscellaneous')], unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='auctions',
            name='category',
        ),
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.ManyToManyField(to='auctions.categories'),
        ),
    ]
