# Generated by Django 3.1.2 on 2021-10-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211006_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='id_cat',
        ),
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(choices=[('SP', 'Sport'), ('FO', 'Food'), ('EL', 'Electronic'), ('CA', 'Cars'), ('CL', 'Clothing'), ('HO', 'Homelike')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.ManyToManyField(default=None, to='auctions.categories'),
        ),
    ]
