# Generated by Django 3.1.2 on 2021-10-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211006_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='category',
        ),
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='categories',
        ),
    ]
