# Generated by Django 3.1.2 on 2021-10-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211006_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'SPORT'), (2, 'ELECTRONIC'), (3, 'HOMELIKE'), (4, 'FOOD'), (5, 'CARS')], default=None, null=True),
        ),
    ]
