# Generated by Django 3.1.2 on 2021-10-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20211006_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.CharField(blank=True, choices=[('Sport', 'SPORT'), ('Electronic', 'ELECTRONIC'), ('Homelike', 'HOMELIKE'), ('Food', 'FOOD'), ('Cars', 'CARS')], default=None, max_length=15, null=True),
        ),
    ]
