# Generated by Django 3.1.2 on 2021-10-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211014_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='auc_bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('auc_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('auction_id', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='auctions',
            name='comment',
            field=models.ManyToManyField(blank=True, to='auctions.Comment'),
        ),
    ]
