# Generated by Django 3.1.2 on 2021-10-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20211017_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='init_price',
            field=models.IntegerField(blank=True, default=models.IntegerField(), null=True),
        ),
    ]
