# Generated by Django 3.1.2 on 2021-10-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20211017_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='winner',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
