# Generated by Django 3.1.2 on 2021-10-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auctions_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='active',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
