# Generated by Django 3.1.2 on 2021-10-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctions_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='winner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
