# Generated by Django 3.1.2 on 2021-10-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20211019_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='comment',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='auctions.Comment'),
        ),
    ]
