# Generated by Django 3.1.2 on 2021-10-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20211019_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='active',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
