# Generated by Django 3.1.2 on 2021-10-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20211019_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='winner',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
