# Generated by Django 3.1.2 on 2021-10-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20211019_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.ImageField(blank=True, default='images', null=True, upload_to='media'),
        ),
    ]
