# Generated by Django 3.1.2 on 2021-10-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20211019_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='active',
        ),
        migrations.RemoveField(
            model_name='auctions',
            name='winner',
        ),
        migrations.AddField(
            model_name='auctions',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='comment',
            field=models.ManyToManyField(blank=True, to='auctions.Comment'),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.ImageField(blank=True, default='images', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='init_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
