# Generated by Django 3.1.2 on 2021-10-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20211019_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='status',
            new_name='state',
        ),
        migrations.AddField(
            model_name='auctions',
            name='winner',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
